hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 4
lr: 5e-5
num_epoch: 20
length: 512
p: 0.3
seed: 42
device: "cuda"
model_name: "bert-base-cased" # bert-large-cased roberta-large

accum_iter: 8
weight_decay: 0.01
use_loss_weight: False
use_scheduler: True
warmup_late: 0.1

post_sentence_padding: True
add_sep_between_sentences: True

multi_view: True
kl_weight: 0.6
kl_t: 1

test: "2003" # 2003, 2023, crossweigh valid

local_model: "model/epoch19.pth" # "outputs\\bert_finetuning\\yyyy-mm-dd\\hh-mm-ss\\model\\epochx.pth"
test_batch: 4
loop: 101
pred_p: 0.1
vote: majority

huggingface_cache: "D:/huggingface/cashe"
visible_devices: "0"
output_path: "./many_preds.txt"