hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 2
lr: 5e-5
num_epoch: 10
length: 512
p: 0
seed: 42
device: "cuda"
model_name: "bert-large-cased"

accum_iter: 16
weight_decay: 0.01
use_loss_weight: True
use_scheduler: True
warmup_late: 0.1

pre_sentence_padding: False
post_sentence_padding: True
add_sep_between_sentences: True

test: "2003" # 2003, 2023, crossweigh valid

local_model: "C:\\Users\\chenr\\Desktop\\python\\subword_regularization\\outputs\\bert_finetuning\\2023-12-26\\02-35-16\\model\\epoch6.pth"
loop: 1
pred_p: 0
vote: majority