hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 16
lr: 3e-5
num_epoch: 50
length: 512
p: 0
seed: 42
device: "cuda"
model_name: "bert-base-cased"

weight_decay: 0
use_loss_weight: True
use_scheduler: True
num_warmup_steps: 50

test: "2003" # 2003, 2023, crossweigh valid

local_model: "C:\\Users\\chenr\\Desktop\\python\\subword_regularization\\outputs\\bert_finetuning\\2023-12-24\\21-05-47\\model\\epoch19.pth"
loop: 1
pred_p: 0
vote: majority
only_non_train_split: False