hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 16
lr: 3e-5
num_epoch: 5
length: 512
p: 0
seed: 42
device: "cuda"
model_name: "bert-base-cased"
stop_word: False
as_aug: False
boi1: False

use_scheduler: False
warmup_t: 10
lr_min: 1e-7
warmup_lr_init: 1e-6

test: "2003" # 2003, 2023, crossweigh valid

local_model: "C:\\Users\\chenr\\Desktop\\python\\subword_regularization\\outputs\\bert_finetuning\\2023-12-23\\23-17-23\\model\\best.pth"
loop: 1
pred_p: 0
vote: majority
only_non_train_split: False