hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 20
lr: 3e-5
num_epoch: 100
length: 128
p: 0.3
seed: 42
device: "cuda"
model_name: "bert-base-cased"
stop_word: True
as_aug: True
test: "2003" # 2003, 2023, crossweigh

use_scheduler: True
warmup_t: 10
lr_min: 1e-7
warmup_lr_init: 1e-6

path: "C:/Users/chenr/Desktop/python/subword_regularization/outputs/train_pred_eval/p3_long/model/epoch49.pth"