hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 2
lr: 5e-5
num_epoch: 10
length: 512
p: 0.1
seed: 42
device: "cuda"
model_name: "bert-large-cased"

accum_iter: 16
weight_decay: 0.01
use_loss_weight: False
use_scheduler: True
warmup_late: 0.1

pre_sentence_padding: False
post_sentence_padding: True
add_sep_between_sentences: True

test: "2003" # 2003, 2023, crossweigh valid

local_model: "model\\BertLargeNormal.pth" # "outputs\\yyyy-mm-dd\\hh-mm-ss\\model\\epochx.pth"
test_batch: 4
loop: 101
pred_p: 0.1
vote: majority

huggingface_cache: "D:\\huggingface\\cashe"