hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

get_rate: 1


batch_size: 20
lr: 5e-5
num_epoch: 60
length: 128
p: 0.3
seed: 42
device: "cuda"
model_name: "bert-base-cased"
stop_word: False
test: "2003"

use_scheduler: False
warmup_t: 5
lr_min: 1e-7
warmup_lr_init: 1e-6

path: "C:/Users/chenr/Desktop/python/subword_regularization/outputs/train_pred_eval/p0/model/best.pth"