hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 20
lr: 1e-5
num_epoch: 30
length: 512
p: 0.1
seed: 42
device: "cuda"
model_name: "Gladiator/roberta-large_ner_conll2003"
stop_word: False
as_aug: False
boi1: False

test: "2003" # 2003, 2023, crossweigh valid

use_scheduler: False
warmup_t: 10
lr_min: 1e-7
warmup_lr_init: 1e-6

loop: 1
pred_p: 0.1
vote: majority
only_non_train_split: False